on:
  push:
    branches:
      - main
  pull_request:
  release:
    types:
      - published
  workflow_dispatch:
    inputs:
      name:
        description: "Manual trigger"
        required: true

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm install
      - run: npm run compile

  test:
    if: github.event_name == 'push' || github.event_name == 'pull_request'
    strategy:
      fail-fast: false
      matrix:
        include:
          - ros: foxy
    runs-on: ubuntu-20.04
    needs: [build]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - uses: ros-tooling/setup-ros@v0.3
        with:
          required-ros-distributions: ${{ matrix.ros }}
      - run: npm install
      - run: xvfb-run -a npm test
        if: runner.os == 'Linux'
      - run: npm test
        if: runner.os != 'Linux'
      - uses: gaurav-nelson/github-action-markdown-link-check@v1

  archive-vsix:
    runs-on: ubuntu-20.04
    needs: [test]
    if: github.event_name == 'push' || github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm install
      - run: |
          npm install vsce -g
          npm run compile
          vsce package -o vscode-ros-dev.vsix
      - uses: actions/upload-artifact@v1
        with:
          name: vscode-ros-dev-vsix
          path: vscode-ros-dev.vsix

  publish-vsix:
    runs-on: ubuntu-20.04
    if: github.event_name == 'release' && github.event.action == 'published' && github.repository == 'nonanonno/vscode-ros2'
    needs: [build]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm install
      - run: |
          npm install vsce -g
          npm run compile
          vsce publish -p ${{secrets.VSCE_PAT}}
